[#chapter00-before]

== Préface

Cet document est mis à disposition par Alexandre Rousseau sous licence Creative Commons Attribution - Partage dans les Mêmes Conditions 4.0 International. Pour accéder à une copie de cette licence, merci de vous rendre à l’ http://creativecommons.org/licenses/by-sa/4.0/[adresse suivante] ou envoyez un courrier à Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA. Tout le code source de ce document (rédigé en https://asciidoctor.org/[AsciiDoctor]) est disponible sur http://git.rousseau-alexandre.fr/madeindjs/it_report[ce répertoire Git].

=== Remerciements

J'adresse mes remerciements aux personnes qui m'ont aidé dans la réalisation de ce mémoire.

En premier lieu, je remercie M. Alpha, professeur à l'université de ABC. En tant que Directeur de mémoire, il m'a guidé dans mon travail et m'a aidé à trouver des solutions pour avancer.

Je remercie aussi Mme Beta, directrice de l'entreprise DEF, pour sa collaboration en me fournissant des données précises sur le marché de XXX.

Je souhaite particulièrement remercier Mme Gamma pour sa précieuse aide à la relecture et à la correction de mon mémoire.

=== Introduction

Passionné et autodidacte, mon implication personnelle m'a permis d'évoluer en tant que développeur. Issue d'une reconversion professionnelle, je suis actuellement en CDI chez Gac Technology. Gac est une startup lyonnaise créée en 2010 et qui compte maintenant presque 50 salariés. Elle vend plusieurs produits en mode SAAS (_Software As A Service_) qui permettent la gestion de moyen à grands parcs automobile, téléphonique  et immobilier.

image:gac.svg[logo, 200]

Gac Technology possède beaucoup de clients renommés comme Bouygues, SNCF, Véolia ou encore l'Olympique Lyonnais. La base de données de Gac est constituée de plus de 200 tables dont la plus grosse contient plus de cent millions d'entrées. Cela est donc pour moi une formidable opportunité de me perfectionner sur la construction de requêtes SQL performante et d'un code optimisé.

A dehors de mon travail je participe aussi à quelques projets projets Open Source comme:

- API on Rails 5, un livre que j'ai traduis et adapté à partir de _"APIs on Rails - Building REST APIs with Rails"_ qui traite des meilleurs pratiques pour construire une API en utilisant Rails
- Crystagiri, un parseur de document HTML écrit en Crystal et suivi par presque 100 personnes sur Github
- Raspberry Cook, une plateforme de partage de recettes de cuisine qui m'a permis de m'auto-former sur Ruby on Rails et l'autho-hébergement d'une application sur Linux
- et bien d'autres choses disponibles sur https://github.com/madeindjs[github.com/madeindjs]

Je donnes aussi des cours à propos de Ruby On Rails sur https://superprof.fr[superprof.fr]. Aujourd'hui, je peux donc affirmer que ma passion me permet de m'épanouir et me spécialiser.
