[#chapter08-conclusion]
== Conclusion générale

Afin de clôturer ce mémoire, je vais dresser un bilan de mon expérience au sein d'iSignif.

=== Quelques chiffres

// TODO


=== Perspectives de iSignif

Nous avons déjà réussi à rendre notre projet viable puisque, comme je l'ai montré plus haut,  nous générons quelques bénéfices.

Nous recherchons à développer notre activité en réalisant des partenariats avec d'autres LegalTech. C'est le cas de l'entreprise "V pour Verdict", spécialisée dans le recours collectif et qui souhaiterait automatiser leurs significations. Nous allons donc très prochainement ouvrir une API documentée leur permettant de signifier des actes.

La construction de cette API nous mène aussi à une réflection de notre interface. En effet, c'est l'opportunité de créer une interface _Single Page Application_ qui sera plus fluide.

De plus, nous réfléchissons à rendre notre outil Open-Source afin de rassurer nos clients sur nos traitements et aussi de proposer notre application aux grands groupes qui souhaiteraient l'utiliser avec leur propre réseau d'huissiers.

=== Retour d'experience

Avec un peu de recul, je sais que j'ai commis quelques erreurs. Cette section a donc pour but d'être un retour constructif sur mon expérience.

Tout d'abord, je pense que j'ai fourni une première version trop complète. Dans l'entreprenariat, une citation connue est:

> Fake it until you make it.

Cette phrase, qui peut se traduire par "Fais semblant tant que tu ne l'as pas réalisé", s'illustre parfaitement par l'exemple de la création de la société Dropbox (fournisseur de stockage dans le cloud) qui est née suite à la création d'une vidéo promotionnelle simulée avec deux machines virtuelles. Dropbox a créé son produit une fois qu'il avait testé la validité de son idée sans développement.

Ainsi j'ai pris trop de risques car nous n'avions pas confronté notre idée sur "le terrain".


Les apports professionnels d’une telle expérience sont évidents. Au delà de m'avoir permis d'acquérir une expérience professionnelle supplémentaire, j'ai pu expérimenter des technologies au sein d'un projet personnel. Ces expérimentations m'ont permis de réinvestir ces nouvelles compétences dans mon travail en tant que développeur.

Cela a aussi été l’occasion d'avoir des responsabilités sur un projet d'une certaine envergure qui donne un tout autre sens au métier de développeur. J'ai ainsi pris conscience qu'une fonctionnalité doit servir en terme de *business*.

Personnellement iSignif m'a permis de *sortir de ma zone de confort* et de découvrir l’*entrepreneuriat* sans prendre trop de risques puisqu'il n'y avait pas d'enjeu financer.


Dans une perspective à long terme, je souhaite continuer de suivre le projet tout en déléguant une partie de plus en plus importante à des développeurs externes. Je me concentrerai donc uniquement sur les choix stratégiques de l'entreprise.
