[#chapter00-before]

== Préface

=== Introduction

Dans le souhait de me former et de progresser continuellement, je me suis inscrit sur le site https://cofondateur.fr[cofondateur.fr]. Ce réseau social met en relation des entrepreneurs qui cherchent des développeurs pour construire leurs idées. C’est ainsi que j'ai créé une _LegalTech_ :footnote:[startup dans le domaine du droit] qui a pour but de mettre en relation des avocats et des huissiers afin de simplifier le processus de signification. Cette excellente opportunité me permet d'avoir plusieurs rôles au sein d'une structure:

- En tant qu’associé et directeur technique, je participe aux décisions stratégiques de l’entreprise
- En tant que directeur technique, j’ai pour mission de faire des choix techniques cohérents afin d’assurer la pérennité de notre produit
- En tant que DPO _(Délégué à la Protection des Données)_, je suis chargé de veiller au respect des données et à la mise en conformité de notre outil.En tant que développeur,

J’ai donc décider de construire mon mémoire uniquement sur ce projet car il met en avant la construction d’un projet de A à Z. Au sein de ce projet, j'ai eu le rôle de référent technique et j'ai donc eu "carte blanche" pour la réalisation du produit.

J’ai fais le choix d’organiser mon mémoire de façon chronologique (dans la mesure du possible). C’est-à-dire:

* la planification du projet
* le développement du projet
* la mise en place du serveur de production
* la collecte des retours utilisateurs
* la promotion du produit

=== licence

Cet document est mis à disposition par Alexandre Rousseau sous licence Creative Commons Attribution - Partage dans les Mêmes Conditions 4.0 International. Pour accéder à une copie de cette licence, merci de vous rendre à l’ http://creativecommons.org/licenses/by-sa/4.0/[adresse suivante] ou envoyez un courrier à Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.

Tout le code source de ce document (rédigé en https://asciidoctor.org/[AsciiDoctor]) est disponible sur http://git.rousseau-alexandre.fr/madeindjs/it_report[ce repertoire Git].

=== Remerciements
