[#chapter06-improve]
== Amélioration continue
// QUESTION: Est-ce que le titre est juste?

// === Développement Dirigé par les test

// Comme je l’évoquait lors de la réunion de pré-lancement, il était capital de maintenir une certaine qualité de nos services. Je me suis donc imposé le _workflow_ du développement dirigé par les tests.

=== RGPD

2018 fut l’année de la mise en place du Règlement général sur la protection des données (RGPD). Entrée en vigueur le 25 mai, ce texte réglementaire européen couvre, entre autres, le traitement des données personnelles footnote:[Les données personnelle sont toutes les données qui permettent d’identifier quelqu’un].

Les principales nouveautés qu’apporte la RGPD sont:

* le droit à l’oubli
* le droit à la portabilité des données
* le droit à l’opposition de toute opération marketing
* le droit à la rectification des données de l’utilisateur
* le droit d’accès à toutes les données de l’utilisateur

Il faut qu’il y ait un https://www.cnil.fr/fr/devenir-delegue-la-protection-des-donnees[Délégué à la Protection des Données]. la https://www.cnil.fr/[CNIL] footnote:[La Commission nationale de l’informatique et des libertés est l’autorité française qui est chargée de veiller à ce que l’informatique.] précise que le délégué . J’ai donc choisit de me porter volontaire pour ce rôle (Voir annexe)

Dans mon cas, les principales obligations qui m’incombent sont les suivantes:

* l’utilisateur doit pouvoir effacer toutes les données de l’application qui le concerne https://gdpr-info.eu/art-17-gdpr/[Chapitre 3, Article 17]
* l’utilisateur doit pouvoir conn // TDOD
* nous devons stocker le minimum de données possible

=== Le droit à l’oubli

Le droit à l'oubli est l'une des plus grosse fonctionnalité demandée par la CNIL. https://gdpr-info.eu/art-17-gdpr/[L’article 17 de la RGPD] nous oblige à implémenter une fonctionnalité qui doit permettre à l’utilisateur d’effacer toutes ses données rapidement. La ou cela se complique, c’est que la RGPD nous oblige aussi à demander la suppression des données chez des fournisseurs tiers (comme Stripe dans mon cas).

La difficulté de cette fonctionnalité est de supprimer les données liées à l’utilisateur sans impacter les données qui sont liées aux autres utilisateurs. Concrètement, cela signifie que lorsqu’un huissier de justice décide de supprimer son compte, il faut:

* supprimer son compte et ses données (logique)
* supprimer toutes ses factures
* supprimer les significations qu’il a effectué
* supprimer ses données chez Stripe

Cependant je ne peux pas supprimer les significations puisqu’elles doivent être conservée pour l’avocat qui a demandé la signification de son acte. C’est pour cela que j’ai préféré l’*anonymisation* des données.

Etant un fan du _Test Driven Development_. J’ai donc commencé par construire le test.

[source, ruby]
.test/models/bailiff_test.rb
----
test 'should anonymize and not destroy record' do
  old_user = @bailiff.as_json

  # on verifie que l'huissier n'est pas supprime en base
  assert_no_difference('Bailiff.count') { @bailiff.destroy }

  # on verifie que tous les champs suivants on ete modifies
  %i[email firstname lastname siret company_name town zip_code address_2 address_1].each do |field|
    assert_not_equal old_user[field], @bailiff.send(field)
  end

  # et pour terminer, un champ 'deleted' a dut etre passe a 'true'
  assert @bailiff.deleted
end
----

J’ai donc simplement surchargé la méthode `User#destroy` et utilisé la librairie `Faker` pour générer des données factices:

[source, ruby]
.app/models/user.rb
----
def destroy
  # ...
  update_attributes(
    email: new_email,
    firstname: Faker::Name.first_name,
    lastname: Faker::Name.last_name,
    siret: Faker::Company.french_siret_number,
    # ...
    deleted: 1
  )
  save
end
----

Et voilà, la mise en conformité est faite. L’huissier ou l’avocat pourra supprimer son compte et les données seront conservées. En revanche, il sera impossible de retrouver l’utilisateur correspondant à ces données.

En plus de cela, j'ai aussi utilisé l'API de Stripe en faisant un appel à leur API pour supprimer leur données lors de la suppression mais je ne le détaillerai pas ici.

==== Le droit à la portabilité et à l'accès des données de l’utilisateur

Afin de respecter cette norme, j'ai tout simplement choisis de proposer d'afficher la page d'accès aux information de l'utilsateur au format JSON. En utilisant la https://github.com/Netflix/fast_jsonapi[librairie de serialization des données de Netflix], j'ai ainsi convertit le model `User` au format JSON en incluant toutes ses liaison. Ainsi, en un clic, l'utilisateur peut obtenir toutes ses donnéesen incluant ses actes, ses messages et les significations qu'il a effectué.

==== Le droit à la rectification des données de l’utilisateur

// TODO

==== Le droit d’accès à toutes les données

// TODO


=== Déploiement continu

Afin d’être le plus réactif possible, j’ai voulu mettre en place un outil afin d’automatiser les mises en production. Cela est un énorme avantage car il permet de mettre en ligne un correctif ou une évolution très rapidement. De plus, automatiser permet de réduire le risque de l’erreur humaine ( https://www.reddit.com/r/webdev/comments/5rd79m/gitlab_employee_just_ran_rm_rf_on_their/[et cela est vite arrivé]...).

Pour cela, j’ai utilisé la librairie https://capistranorb.com[Capistrano]. Capistrano est un outil écrit en Ruby qui permet d’automatiquement le déploiement en s’appuyant sur Git (rappelez vous de mon utilisation de Git Flow). Il va donc:

* *Cloner* le répertoire Git afin de récupérer la dernière version du code source
* Lancer les *migrations* sur la base de données
* *Minifier* footnote:[Il s’agit de concateiner les fichiers texte en un seul afin de réduire le nombre de requête HTTP et d’améliorer la vitesse de chargement] les fichiers JavaScript et CSS
* Faire des liens symboliques sur les documents que les utilisateurs ont envoyés sur le serveur

La librairie se met en place très facilement, voici un extrait de ma configuration

[source, ruby]
.config/deploy.rb
----
set :application, "iSignif"
set :repo_url, "http://git.rousseau-alexandre.fr/iSignif/Website.git"
append :linked_files, 'config/database.yml' , 'config/initializers/secret_token.rb', 'config/secrets.yml'
append :linked_dirs, 'public/uploads'
----

=== Retours des utilisateurs

// TODO
